/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_czh_ffmpeg_mediakit_MediaKit */

#ifndef _Included_com_czh_ffmpeg_mediakit_MediaKit
#define _Included_com_czh_ffmpeg_mediakit_MediaKit
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_czh_ffmpeg_mediakit_MediaKit
 * Method:    getAvcodecConfigurationNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_czh_ffmpeg_mediakit_MediaKit_getAvcodecConfigurationNative
  (JNIEnv *, jobject);

/*
 * Class:     com_czh_ffmpeg_mediakit_MediaKit
 * Method:    decodeNative
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_czh_ffmpeg_mediakit_MediaKit_decodeNative
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
